version: "3.8"
services:
  python:
    container_name: verilog_toolchain
    image: verilog/toolchain
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    deploy:
        restart_policy:
            condition: on-failure
    volumes:
      - /mnt/f/private/git/tt04-verilog-project:/mnt/tt04-verilog-project
